version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./docker_data/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env.db

  redis:
    image: redis:6.2.1-alpine

  backend:
    build:
      context: ./sosmed_backend
      dockerfile: Dockerfile
    command: npm start
    expose:
      - 8001
    depends_on:
      - db
      - redis
    env_file:
      - .env.backend
    volumes:
      - ./docker_data/nginx/assets:/app/nginx/assets

  frontend:
    build:
      context: ./sosmed_frontend
      dockerfile: Dockerfile
    command: npm start
    expose:
      - 8000
    env_file:
      - .env.frontend
    depends_on:
      - backend

  nginx:
    build: ./nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./docker_data/nginx/:/var/www/sosmed_backend/
