version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./docker_data/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env.db

  redis:
    image: redis:6.2.1-alpine

  backend:
    build:
      context: ./sosmed_backend
      dockerfile: Dockerfile
    command: npm run start
    expose:
      - 8001
    depends_on:
      - db
      - redis
    env_file:
      - .env.backend.prod
    volumes:
      - ./docker_data/nginx/backend/assets:/app/nginx/assets

  frontend:
    build:
      context: ./sosmed_frontend
      dockerfile: Dockerfile
    command: npm run build_serve
    env_file:
      - .env.frontend.prod
    depends_on:
      - backend
    volumes:
      - ./docker_data/nginx/frontend:/app/build

  nginx:
    build: ./nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    volumes:
      - ./docker_data/nginx/frontend:/var/www/sosmed_frontend/
      - ./docker_data/nginx/backend:/var/www/sosmed_backend/
      - ./docker_data/nginx/keys/:/app/keys
