FROM nginx:mainline-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
# RUN mkdir -p /etc/nginx/sites-available/klipboard.me/
# COPY nginx.conf /etc/nginx/sites-available/klipboard.me/
