FROM nginx:1.19.7-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
# RUN mkdir -p /etc/nginx/sites-available/webdev-sosmed.id/
# COPY nginx.conf /etc/nginx/sites-available/webdev-sosmed.id/